name: parichaya_frontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  mask_text_input_formatter: ^2.4.0
  flutter_native_splash: ^2.2.17
  local_auth: ^2.1.3
  pin_code_fields: ^7.4.0
  web_socket_channel: ^2.3.0
  qr_flutter: ^4.0.0
  connectivity_plus: ^3.0.3
  intl: ^0.18.0
  font_awesome_flutter: ^10.4.0
  device_info_plus: ^8.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  color_dark: "#0F0F0F"
  image_dark: assets/images/dark-splash.png

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/CTZ.png
    - assets/images/DVL.png
    - assets/images/NID.png

  fonts:
      - family: CustomIcons
        fonts:
          - asset: assets/fonts/CustomIcons.ttf
      - family: CustomIdCardIcon
        fonts:
          - asset: assets/fonts/CustomIdCardIcon.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
